Repository konflux-ci/integration-service, pull requests merged in 2023-10, with the labels that each got.

#310 feat: new grafana panel for release latency seconds
  config/grafana/dashboards/integration-service-dashboard.json
  controllers/snapshot/snapshot_adapter.go
  gitops/snapshot.go
  gitops/snapshot_test.go
  metrics/integration.go
  metrics/integration_test.go
Labels: lgtm

#344 fix(STONEINTG-632): accept warning test result as passed
  helpers/integration.go
  helpers/integration_test.go
Labels: lgtm

#273 feat(STONEINTG-488): react to application component deletion
  config/rbac/role.yaml
  controllers/component/component_adapter.go
  controllers/component/component_adapter_test.go
  controllers/component/component_controller.go
  controllers/component/component_controller_test.go
  controllers/component/component_suite_test.go
  controllers/component/predicates.go
  docs/component_controller.md
  gitops/snapshot.go
Labels: lgtm

#340 fix(STONEINTG-631): add release, deployment, GCL status conditions
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  docs/snapshot-controller.md
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm

#342 hotfix: remove HandleLoaderError from logger struct
  controllers/snapshot/snapshot_controller.go
  helpers/errorhandlers.go
Labels: lgtm

#335 fix(stoneintg-582): do not requeue SEB if snapshot cannot be found
  controllers/binding/snapshotenvironmentbinding_controller.go
  controllers/binding/snapshotenvironmentbinding_controller_test.go
  helpers/errorhandlers_test.go
Labels: lgtm

#338 fix(stoneintg-584): do not requeue SEB if application cannot be found
  controllers/binding/snapshotenvironmentbinding_controller.go
  controllers/binding/snapshotenvironmentbinding_controller_test.go
Labels: lgtm

#327 feat(STONEINTG-538): refactor EnsureAllIntegrationTestPipelinesExist()
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm

#345 fix(STONEINTG-532): correct panel display release create
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm

#347 feat(statusreporting): add feature flag
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
Labels: lgtm

#348 Merge feature branch "statusreport" into main
  controllers/controllers.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  controllers/statusreport/statusreport_controller.go
  controllers/statusreport/statusreport_controller_test.go
  controllers/statusreport/statusreport_suite_test.go
  docs/statusreport-controller.md
  git/github/github.go
  git/github/github_test.go
  gitops/snapshot.go
  gitops/snapshot_predicate.go
  gitops/snapshot_predicate_test.go
  status/reporters.go
  status/reporters_test.go
  status/status.go
  status/status_test.go
Labels: lgtm

#346 refactor(STONEINTG-539): EnsureCreationOfEnvironments
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm

#358 refactor(STONEINTG-621): move intg. test status code into pkg
  Dockerfile
  controllers/binding/snapshotenvironmentbinding_adapter.go
  controllers/binding/snapshotenvironmentbinding_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  gitops/snapshot.go
  gitops/snapshot_integration_tests_status.go
  gitops/snapshot_integration_tests_status_test.go
  gitops/snapshot_test.go
  pkg/README.md
  pkg/integrationteststatus/integration_test_status.go
  pkg/integrationteststatus/integration_test_status_test.go
  pkg/integrationteststatus/integrationteststatus_enumer.go
  pkg/integrationteststatus/integrationteststatus_suite_test.go
  status/reporters.go
Labels: lgtm

#361 fix(STONEINTG-585): update owner reference to snapshot for SEBs
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm

#362 refactor(STONEINTG-539): abstract detection of ephemeral env
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm

#360 refactor(STONEINTG-539): update wording for ephemeral environments
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/snapshot/snapshot_controller.go
  docs/snapshot-controller.md
Labels: lgtm

#367 chore: add link to codecov in PR template
  docs/pull_request_template.md
Labels: lgtm

#368 fix(STONEINTG-583): add status conditions when converting to v1beta1
  api/v1alpha1/integrationtestscenario_conversion.go
Labels: lgtm

#371 fix(STONEINTG-583): add status.conditions to existing ITS
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
Labels: lgtm

#359 feat(STONEINTG-613): remove status report from PLR controller
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_controller.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  controllers/statusreport/statusreport_controller.go
  docs/statusreport-controller.md
  git/github/github.go
  git/github/github_test.go
  status/format.go
  status/format_test.go
  status/reporters.go
  status/reporters_test.go
  status/status.go
  status/status_test.go
Labels: lgtm

#372 feat(STONEINTG-535): SLI successful/failed ephemeral environment deloyments
  controllers/binding/snapshotenvironmentbinding_adapter.go
  metrics/integration.go
Labels: lgtm, size: XS

#379 feat(STONEINTG-533): add 2 panels for SLO #3
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: L

#373 fix(STONEINTG-641): use snapshot for SEB components directly
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  gitops/binding.go
  gitops/binding_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: L

#382 fix(STONEINTG-666): update kube-rbac-proxy to v0.15.0
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, size: XS

#385 fix(STONEINTG-533: Fix parsing error in SLO 5 expression
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: XS, jira/valid-reference

#391 fix(STONEINTG-533): fix parsing error in SLO 5 expression
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: XS

#341 feat(STONEINTG-599): add finalizers to Integration PLR
  controllers/binding/snapshotenvironmentbinding_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/snapshot/snapshot_adapter.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_controller.go
  docs/integration_pipeline_controller.md
  docs/statusreport-controller.md
  helpers/finalizers.go
  helpers/integration.go
  pkg/integrationteststatus/integration_test_status.go
  pkg/integrationteststatus/integration_test_status_test.go
  pkg/integrationteststatus/integrationteststatus_enumer.go
  status/reporters.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
  tekton/predicates.go
  tekton/predicates_test.go
  tekton/utils.go
Labels: lgtm, size: XL, size: XXL

#395 docs: remove unnecessary node
  docs/integration_pipeline_controller.md
Labels: lgtm, size: XS

#389 fix(STONEINTG-583): set scenario status to valid if undefined
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
Labels: lgtm, size: XS

#390 feat(STONEINTG-536): add 2 panels for SLO 6
  config/grafana/dashboards/integration-service-dashboard.json
Labels: do-not-merge/work-in-progress, size: L
