Repository konflux-ci/integration-service, pull requests merged in 2023-11, with the labels that each got.

#394 feat(STONE-535): Adding panel for SLI SEB Total
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: M

#399 fix(STONEINTG-643): don't process snapshot with nonexisting app
  controllers/snapshot/snapshot_controller.go
  controllers/snapshot/snapshot_controller_test.go
Labels: lgtm, size: M, size: S

#387 fix(STONEINTG-640): limit ITS name length
  PROJECT
  api/v1beta1/integrationtestscenario_suite_test.go
  api/v1beta1/integrationtestscenario_webhook.go
  api/v1beta1/integrationtestscenario_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
Labels: lgtm, size: XL

#400 feat(EC-202): Proceed if Chains could not sign
  docs/build_pipeline_controller.md
  tekton/predicates.go
  tekton/predicates_test.go
  tekton/utils.go
Labels: lgtm, size: XS

#397 fix(STONEINTG-649): remove component in integrationpipeline controller
  controllers/buildpipeline/buildpipeline_controller.go
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_controller.go
Labels: lgtm, size: XS, size: L, size: M, size: S

#401 fix(STONEINTG-668): update the status reporter with new "Deleted" state
  status/reporters.go
  status/reporters_test.go
Labels: lgtm, size: XS

#404 chore: add kasemAlem as reviewer on dependabot PRs
  .github/dependabot.yml
Labels: lgtm, size: XS

#381 fix(STONEINTG-642) stop reconciliation if env is not found for ITS
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  helpers/errorhandlers.go
  helpers/errorhandlers_test.go
Labels: lgtm, size: L, size: M

#403 feat(STONEINTG-635): increase snapshot code coverage
  controllers/binding/snapshotenvironmentbinding_adapter_test.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/component/component_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/statusreport/statusreport_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
Labels: lgtm, size: XXL

#411 fix(snapshot_predicate_test): remove unneeded provisioning
  gitops/snapshot_predicate_test.go
Labels: lgtm, size: XS

#357 feat(stoneintg-600): Add finalizers to build pipeline runs
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller.go
  controllers/buildpipeline/buildpipeline_controller_test.go
  docs/build_pipeline_controller.md
  go.mod
  helpers/integration.go
  tekton/predicates.go
  tekton/predicates_test.go
Labels: lgtm, size: L, size: XL

#419 fix(STONEINTG-644): log message at info level when one component buil…
  gitops/snapshot.go
Labels: lgtm, size: XS

#406 feat(stoneintg-628): metric for time to start plr with ephemeral env
  controllers/binding/snapshotenvironmentbinding_adapter.go
  metrics/integration.go
  metrics/integration_test.go
Labels: size: M

#405 fix(STONEINTG-649): remove finalizer when component is missing
  controllers/buildpipeline/buildpipeline_controller.go
  controllers/buildpipeline/buildpipeline_controller_test.go
Labels: lgtm, size: S

#423 feat(stoneintg-628): add histogram panels for pipelinerun latency
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: L

#433 fix(STONEINTG-561): bug in naming convention of metrics
  config/grafana/dashboards/integration-service-dashboard.json
  metrics/integration.go
Labels: lgtm, size: XS

#435 fix(size): add 20% to thresholds
  .github/workflows/size.yaml
Labels: lgtm, size: XS

#427 fix(STONEINTG-684): remove finalizers if Snapshot can't be found
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_controller.go
  controllers/integrationpipeline/integrationpipeline_controller_test.go
Labels: lgtm, size: M

#439 fix(grafana): update SLI title for static env
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: XS

#440 fix(STONEINTG-693): stop collisions in buildpipeline adapter tests
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller_test.go
Labels: lgtm, size: S

#437 fix(STONEINTG-689): skip update if *StatusAdapter fails
  status/reporters.go
Labels: lgtm, size: XS

#441 fix(binding-PLR): missing build labels/annotations
  controllers/binding/snapshotenvironmentbinding_adapter.go
Labels: lgtm, size: XS

#445 fix(metrics): don't count PLR re-run into statistics
  controllers/binding/snapshotenvironmentbinding_adapter.go
  controllers/snapshot/snapshot_adapter.go
  gitops/snapshot.go
  metrics/integration.go
Labels: lgtm, size: XS

#444 fix(STONEINTG-693): don't start controllers in unit tests
  controllers/binding/snapshotenvironmentbinding_controller_test.go
  controllers/component/component_controller_test.go
  controllers/integrationpipeline/integrationpipeline_controller_test.go
  controllers/scenario/scenario_controller_test.go
  controllers/snapshot/snapshot_controller_test.go
  controllers/statusreport/statusreport_controller_test.go
Labels: lgtm, size: XS

#436 fix(rhtapbugs-975): point test plr params to source repo
  controllers/buildpipeline/buildpipeline_adapter_test.go
  tekton/utils.go
  tekton/utils_test.go
Labels: lgtm, size: XS, size: M

#418 fix(stoneintg-645): failed to get component for build pipeline
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller.go
  controllers/component/component_controller.go
Labels: lgtm, size: XS, size: S

#447 fix(SEB): mark snapshot as running tests
  controllers/binding/snapshotenvironmentbinding_adapter.go
Labels: lgtm, size: XS

#451 feat: add sonar cloud properties
  .sonarcloud.properties
Labels: lgtm, size: XS
