Repository konflux-ci/integration-service, pull requests merged in 2023-12, with the labels that each got.

#448 refactor(reporters): separate github reporters
  status/reporters.go
Labels: lgtm, size: XXL

#459 Revert "fix(rhtapbugs-975): point test plr params to source repo"
  controllers/buildpipeline/buildpipeline_adapter_test.go
  tekton/utils.go
  tekton/utils_test.go
Labels: lgtm, size: M

#456 feat(api): add shortname for ITS
  api/v1beta1/integrationtestscenario_types.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
Labels: lgtm, size: XS

#457 feat(STONEINTG-608): switch to use integration-service PAC secret
  status/reporters.go
Labels: lgtm, size: XS

#460 fix(STONEINTG-692): wait for backup labels in unit tests
  controllers/snapshot/snapshot_controller_test.go
  controllers/statusreport/statusreport_controller_test.go
Labels: lgtm, size: XS

#438 fix(STONEINTG-689): add PR last update snapshot annotation
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  git/github/github.go
  git/github/github_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
  status/reporters.go
  status/reporters_test.go
Labels: lgtm, size: L, size: M, size: S

#443 fix(STONEINTG-646): trigger snapshot reconcile for added its
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: XS, size: M, size: S

#421 fix(STONEINTG-580): handle invalid environments
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: M

#463 fix(STONEINTG-683): update message for status condition SnapshotDeplo…
  controllers/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#458 fix(STONEINTG-654): remove duplication metric SnapshotInvalidTotal
  config/grafana/dashboards/integration-service-dashboard.json
  metrics/integration.go
  metrics/integration_test.go
Labels: lgtm, size: L, size: M

#462 feat(STONEINTG-696): Issue fixes to onborad integration-service to RHTAP
  .gitlint
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: size: XS

#467 fix(STONEINTG-696): let gitlint ingore prs from red-hat-trusted-app-pipeline
  .gitlint
Labels: size: XS

#476 feat(STONEINTG-696): remove the old build pipeline definitions
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm, size: M

#477 fix(metrics): count only created integration PLR
  controllers/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#478 chore(STONEINTG-661): add golangci
  .github/workflows/gosec.yaml
  .github/workflows/pr.yaml
  .golangci.yml
Labels: lgtm, size: XS, size: M

#479 fix(STONEINTG-714): gitops predicates cover all types of events
  gitops/predicates.go
  gitops/predicates_test.go
Labels: lgtm, size: S

#482 fix(STONEINTG-696): add mandatory label to pass EC verify
  Dockerfile
Labels: size: XS
