Repository konflux-ci/integration-service, pull requests merged in 2024-04, with the labels that each got.

#652 feat(STONEINTG-844): link tasks logs to task details in git reports
  status/format.go
  status/format_test.go
  status/status_test.go
Labels: lgtm, size: M

#664 fix(gosec): implicit memory aliasing in for loop
  controllers/scenario/scenario_adapter.go
Labels: lgtm, size: XS

#670 fix: overwrite missing inherited labels
  Dockerfile
Labels: lgtm, size: XS

#651 feat(STONEINTG-843): add consoleURL plr to github checkrun
  git/github/github.go
  git/github/github_test.go
  status/reporter.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: L, size: M, size: S

#653 feat(STONEINTG-578): don't block other ITS test if one of them fails
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  gitops/snapshot.go
  helpers/scenario.go
  helpers/scenario_test.go
Labels: size: L, size: XL, size: S

#662 feat(STONEINTG-872): create integration health dashboard in grafana
  config/grafana/dashboard.yaml
  config/grafana/dashboards/integration-service-health.json
  config/grafana/kustomization.yaml
Labels: size: XL

#668 fix(KFLUXBUGS-1202): use proper project id when talking with GL project
  gitops/snapshot.go
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
Labels: size: XS, size: M, size: S

#626 feat(STONEINTG-781): remove finalizer sooner for integration plr
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  docs/statusreport-controller.md
  pkg/integrationteststatus/integration_test_status.go
  pkg/integrationteststatus/integration_test_status_test.go
Labels: lgtm, size: M, size: XL

#672 fix(STONEINTG-885): add https to developmet console links
  status/format.go
  status/format_test.go
Labels: lgtm, size: XS

#680 fix(STONEINTG-872) add group_left() to fix many-to-one matching issue
  config/grafana/dashboards/integration-service-health.json
Labels: size: XS

#572 feat(STONEINTG-698): Stop provisioning ephemeral environments
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/snapshot/snapshot_controller.go
  docs/snapshot-controller.md
  gitops/environment.go
  gitops/environment_test.go
  helpers/integration.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: XXL

#677 feat(STONEINTG-697): Stop deploying successful snapshot to root envs
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/snapshot/snapshot_controller.go
  docs/snapshot-controller.md
  gitops/binding.go
  gitops/binding_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: XL

#685 fix: clarify error messages in gitlab reporter initialization
  status/reporter_gitlab.go
Labels: lgtm, size: XS
