Repository konflux-ci/integration-service, pull requests merged in 2024-08, with the labels that each got.

#827 feat(STONEINTG-997): save build PLR info to build PLR and snapshot metadata
  docs/build_pipeline_controller.md
  gitops/snapshot.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/buildpipeline/buildpipeline_controller.go
  tekton/build_pipeline.go
  tekton/build_pipeline_test.go
Labels: ok-to-test, size: L, size: M, size: XL

#828 feat(STONEINTG-941): Replace Environment API references
  api/v1alpha1/integrationtestscenario_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/integrationtestscenario_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
Labels: lgtm, size: M

#834 chore(STONEINTG-989): update image to ubi9
  Dockerfile
Labels: lgtm, size: XS

#833 feat(STONEINTG-997): annotate pr group for pr PLR only
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  tekton/build_pipeline.go
  tekton/build_pipeline_test.go
Labels: lgtm, size: XS, size: S

#820 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, ok-to-test, size: S

#837 fix(stoneintg-971): reconciliation invalid image digest err
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
Labels: lgtm, size: XS

#841 fix(STONEINTG-980): consider target branch when overwriting ITS
  gitops/snapshot.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: XS

#851 chore: remove sbom-json-check task from build pipelines
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: S
