Repository konflux-ci/integration-service, pull requests merged in 2024-03, with the labels that each got.

#583 STONEINTG-769: Add GitLab commit status updates for integration tests
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  controllers/statusreport/statusreport_controller.go
  docs/statusreport-controller.md
  gitops/snapshot.go
  go.mod
  go.sum
  status/reporter.go
  status/reporter_github.go
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
  status/status.go
Labels: size: XL, size: XXL

#596 fix(STONEINTG-809): add merge request when judging PR event
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/snapshot/snapshot_adapter.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: XS, size: M, size: S

#606 fix(STONEINTG-769): do not block reconciliation when report fail
  controllers/statusreport/statusreport_adapter.go
  status/status.go
Labels: lgtm, size: XS, size: M

#612 fix(buildpipeline): log details about unsuccessful PLR
  controllers/buildpipeline/buildpipeline_adapter.go
Labels: lgtm, size: XS

#624 fix(errors): support joined error
  helpers/errorhandlers.go
Labels: lgtm, size: XS

#621 fix(STONEINTG-810): rename to Konflux
  status/status.go
  status/status_test.go
Labels: size: XS

#627 fix(STONEINTG-848): drop logic for detecting latest PLR
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: L

#613 fix(STONEINTG-819): don't retry if component label is missing
  controllers/binding/snapshotenvironmentbinding_controller.go
  controllers/snapshot/snapshot_controller.go
  controllers/statusreport/statusreport_adapter.go
  helpers/errorhandlers.go
  loader/loader.go
  loader/loader_test.go
Labels: size: XS

#617 fix(STONEINTG-820): make statusreport controller log for 0 scenarios
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
Labels: lgtm, size: L

#609 feat(STONE-812): url mapping to console url
  status/format.go
  status/format_test.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: L, size: M, size: XL

#630 fix(logs): add missing scenario names
  controllers/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#620 feat(STONEINTG-786): disallow invalid containerImage to be added to component
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
  helpers/errorhandlers.go
  helpers/errorhandlers_test.go
Labels: lgtm, size: L, size: M, size: S

#618 fix(STONEINTG-710): race condition in status update time
  gitops/snapshot.go
  gitops/snapshot_test.go
  status/status.go
  status/status_test.go
Labels: size: XL

#638 fix(RHTAPWATCH-847): some gitlab MR snapshots missed
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: S

#639 fix(STONEINTG-835): don't update running gitlab commitStatus
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
Labels: lgtm, size: L

#644 chore: pin setup-envtest version at working commit to unblock content provider
  Makefile
Labels: lgtm, size: XS

#648 fix(stoneinteg-761): remove ephemeral environment metric
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: L
