Repository konflux-ci/integration-service, pull requests merged in 2024-02, with the labels that each got.

#547 fix(buildPLR): log entry was not logging correctly
  controllers/buildpipeline/buildpipeline_adapter.go
Labels: lgtm, size: XS

#543 chore(worklfows): remove docker build
  .github/workflows/pr.yaml
Labels: lgtm, size: XS

#551 fix(STONEINTG-687): stop reconciliation when app is not found
  controllers/component/component_controller.go
  controllers/component/component_controller_test.go
Labels: lgtm, size: XS

#545 fix(STONEINTG-779): fixes for annotating build PLR
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  helpers/integration.go
  tekton/build_pipeline.go
Labels: size: L

#546 chore(RHTAPWATCH-758): add snapshot garbage collection main loop
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
  go.mod
  go.sum
Labels: lgtm, size: XL, size: XXL

#556 chore: add red-hat-konflux to gitlint ignore list
  .gitlint
Labels: lgtm, size: XS

#560 fix: the misleading log message
  controllers/integrationpipeline/integrationpipeline_adapter.go
  helpers/integration.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: XS

#559 fix(metrics): add more buckets into response metric
  metrics/integration.go
Labels: lgtm, size: XS

#561 feat(RHTAPWATCH-777): add snapshotgc to image
  Dockerfile
Labels: lgtm, size: XS

#552 feat(STONE-577): remove v1alpha1 ITS together with webhook
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/integrationtestscenario_conversion.go
  api/v1alpha1/integrationtestscenario_suite_test.go
  api/v1alpha1/integrationtestscenario_types.go
  api/v1alpha1/integrationtestscenario_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/integrationtestscenario_conversion.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_integrationtestscenarios.yaml
  config/samples/appstudio_v1alpha1_integrationtestscenario.yaml
  config/samples/kustomization.yaml
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
  main.go
Labels: lgtm, size: XXL

#557 fix(STONEINTG-798): use labels to find Snapshots for build pipelineRun
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
  tekton/build_pipeline.go
Labels: lgtm, size: L

#549 fix(STONEINTG-752): don't reconcile unnecessary Integration PLRs
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  helpers/integration.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: L, size: M

#562 chore(RHTAPWATCH-778): add snapshotgc cronjob
  config/rbac/kustomization.yaml
  config/rbac/snapshotgc_rbac.yaml
  config/snapshotgc/kustomization.yaml
  config/snapshotgc/snapshotgc.yaml
Labels: lgtm, size: M

#571 Revert "feat(STONE-577): remove v1alpha1 ITS together with webhook"
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/integrationtestscenario_conversion.go
  api/v1alpha1/integrationtestscenario_suite_test.go
  api/v1alpha1/integrationtestscenario_types.go
  api/v1alpha1/integrationtestscenario_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/integrationtestscenario_conversion.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_integrationtestscenarios.yaml
  config/samples/appstudio_v1alpha1_integrationtestscenario.yaml
  config/samples/kustomization.yaml
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
  main.go
Labels: lgtm, size: XXL

#578 fix: simplify unittest for GetAllTaskRunsWithMatchingPipelineLabel
  loader/loader_test.go
Labels: lgtm, size: S

#580 chore: override variables with env vars when provided
  cmd/snapshotgc/snapshotgc.go
Labels: lgtm, size: XS

#585 fix(STONEINTG-807): report invalid test run into GH
  status/reporters.go
  status/reporters_test.go
Labels: lgtm, size: XS

#573 refactor(STONEINTG-769): prepare for new reporter
  codecov.yml
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  go.mod
  go.sum
  status/format.go
  status/format_test.go
  status/mock_k8sclient_test.go
  status/mock_reporter.go
  status/mock_status.go
  status/reporter.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/reporters_test.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: XXL

#582 fix(STONEINTG-776): [unit-test] point the Snapshot to a non-existent Application
  controllers/snapshot/snapshot_controller_test.go
Labels: lgtm, size: XS

#584 fix(stoneinteg-761): create a new metric to replace static env
  metrics/integration.go
  metrics/integration_test.go
Labels: lgtm, size: S

#590 fix(statusreport): include TestInvalid in evaluation
  controllers/statusreport/statusreport_adapter.go
  gitops/snapshot_predicate.go
Labels: lgtm, size: XS

#592 fix(statusreporting): Revert predicate creation event
  controllers/statusreport/statusreport_adapter.go
  gitops/snapshot_predicate.go
Labels: lgtm, size: XS

#565 fix(STONEINTG-751): add backoff threshold for GH authentication
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/statusreport/statusreport_adapter.go
  helpers/integration.go
  helpers/integration_test.go
Labels: size: XS, size: S

#581 feat(STONE-577): set v1alpha1 its as unservedVersion
  api/v1alpha1/integrationtestscenario_suite_test.go
  api/v1alpha1/integrationtestscenario_types.go
  api/v1alpha1/integrationtestscenario_types_test.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
Labels: lgtm, size: XS, size: L

#594 fix(STONEINTG-819): teach statusreport ctrl to deal with missing label
  controllers/statusreport/statusreport_adapter.go
  loader/loader.go
  loader/loader_test.go
Labels: lgtm, size: XS

#591 fix(RHTAPWATCH-847): support gitlab MR event type labels
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: XS
