Repository konflux-ci/integration-service, pull requests merged in 2024-10, with the labels that each got.

#886 fix(STONEINTG-1048): stop reconciliation when failing to get pr status
  git/github/github.go
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#888 feat(STONEINTG-1033): extend group test info fields
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  status/format.go
  status/format_test.go
Labels: lgtm, size: L

#890 fix(STONEINTG-999): use scenario and snapshot as key of SnapshotRepor…
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: M

#894 fix(STONEINTG-999): annotate snapshot for unrecoverable error
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#895 fix(STONEINTG-1033): fix for format in status report
  status/format.go
Labels: lgtm, size: XS

#896 fix(STONEINTG-1033): fix git provider pull/merge request url
  status/format.go
  status/format_test.go
Labels: lgtm, size: XS

#893 fix(KFLUXBUGS-1340): add branch param from fork to snapshot
  gitops/snapshot.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: XS

#900 fix(STONEINTG-1048): stop reconciliation directly when meeting during preparing group snapshot
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#901 chore(stoneintg-1008): stop referencing/updating spec.containerImage
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: S

#904 Revert "chore(stoneintg-1008): stop referencing/updating spec.containerImage"
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: S

#902 fix(STONEINTG-1048): stop reconciliation for unrecoverable error during group snapshot creation
  git/github/github.go
  helpers/errorhandlers.go
  helpers/errorhandlers_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  status/reporter.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/reporter_gitlab.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: L, size: XL
