Repository konflux-ci/integration-service, pull requests merged in 2024-01, with the labels that each got.

#481 feat(STONEINTG-725): retry for recoverable error when creating relase
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: XS

#496 fix: set build-source-image pipeline param to true
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#495 feat(STONEINTG-703): reset snapshot status conditions when rerunning test
  controllers/snapshot/snapshot_adapter.go
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: S

#483 fix(rhtapbugs-975): use source_url instead of repo_url
  .tekton/integration-service-pull-request.yaml
Labels: lgtm, size: XS

#485 STONEINTG-661: Fix golangci reported issues
  controllers/binding/snapshotenvironmentbinding_adapter_test.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller.go
  controllers/component/component_adapter_test.go
  controllers/snapshot/snapshot_adapter_test.go
  git/github/github_test.go
  gitops/binding_test.go
  gitops/environment_test.go
  gitops/snapshot_integration_tests_status_test.go
  gitops/snapshot_test.go
  helpers/integration_test.go
  loader/loader_test.go
  pkg/integrationteststatus/integration_test_status_test.go
  status/status_test.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: L, jira/valid-reference

#507 fix(STONEINTG-742): don't trigger duplicated integration PLRs
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: XS

#501 feat: add additional buckets to sli 2b histogram
  metrics/integration.go
Labels: size: XS

#502 fix(STONEINTG-737): cleanup related resources after ITS is deleted
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/scenario/predicates.go
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
  controllers/scenario/scenario_controller.go
  docs/scenario-controller.md
  helpers/finalizers.go
  helpers/integration.go
  helpers/integration_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: M, size: XL

#503 fix(STONEINTG-706): don't record PLR starttime for reruns
  controllers/binding/snapshotenvironmentbinding_adapter.go
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: M, size: S

#514 fix(RHTAPBUGS-1091): react to deleted running build PLR
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller.go
  tekton/predicates.go
  tekton/predicates_test.go
Labels: lgtm, size: L

#489 fix(stoneintg-730): Add build PLR annotation for snapshot status
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  helpers/build.go
Labels: lgtm, size: L, size: M

#513 feat(STONE-738): Copy labels+annotations to composite snapshot
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  gitops/snapshot.go
Labels: lgtm, size: M, size: S

#517 refactor(MarkSnapshot*): don't return the same pointer
  controllers/binding/snapshotenvironmentbinding_adapter.go
  controllers/binding/snapshotenvironmentbinding_adapter_test.go
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/snapshot/snapshot_controller.go
  controllers/statusreport/statusreport_adapter.go
  gitops/binding_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
  helpers/integration_test.go
  loader/loader_test.go
Labels: lgtm, size: L

#506 fix(STONEINTG-709): add support missing info of build PLR error
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  helpers/errorhandlers.go
  helpers/errorhandlers_test.go
  tekton/utils.go
Labels: size: XS, size: L, size: M

#515 fix(ocp-names): shorten generated names
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
Labels: lgtm, size: XS

#523 fix(stoneintg-753): requeue release creation until timeout
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: S

#518 fix(STONEINTG-751): don't auth when there is nothing to report
  status/reporters.go
  status/reporters_test.go
Labels: lgtm, size: XS

#535 fix(kube-lint): fix liveness-port check
  .github/.kube-linter-config.yaml
  Dockerfile
  config/manager/kustomization.yaml
Labels: lgtm, size: XS

#534 chore(RHTAPWATCH-729): get namespace release snapshots
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_suite_test.go
  cmd/snapshotgc/snapshotgc_test.go
  go.mod
  go.sum
Labels: lgtm, size: L

#537 chore(RHTAPWATCH-729): get namespace Bindings snapshots
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: L

#532 feat(STONE-734): stop reconcilation for not found applicaiton
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller.go
  tekton/build_pipeline.go
Labels: size: XS, size: L, size: M, size: S

#539 chore(RHTAPWATCH-731): keep newest snapshots
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: L, size: XL

#542 fix(RHTAPBUGS-1119): don't block build PLR removal
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
Labels: lgtm, size: S

#540 chore(RHTAPWATCH-732): delete garbage collected snapshots
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
  go.mod
Labels: lgtm, size: L

#410 (STONEINTG-687): add finalizer to component controller
  controllers/component/component_adapter.go
  controllers/component/component_controller.go
  controllers/component/predicates.go
  controllers/scenario/scenario_adapter_test.go
  helpers/finalizers.go
  helpers/integration.go
  helpers/integration_test.go
Labels: lgtm, size: L
