Repository konflux-ci/integration-service, pull requests merged in 2024-11, with the labels that each got.

#915 fix(STONEINTG-1066): retry when finding application for ITS
  internal/controller/scenario/scenario_controller.go
Labels: lgtm, size: XS

#919 fix: add rpms-signature-scan task to pipelines
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#910 chore(STONEINTG-824) reduce complexity in statusreport adapter
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: M

#925 chore(stoneintg-1079): separate build and test pipeline failures
  config/grafana/dashboards/integration-service-health.json
  internal/controller/buildpipeline/buildpipeline_controller.go
  internal/controller/integrationpipeline/integrationpipeline_controller.go
Labels: lgtm, size: XS

#927 fix: duplicate refID in grafana panel
  config/grafana/dashboards/integration-service-health.json
Labels: lgtm, size: XS

#922 feat(STONEINTG-1071): skip checking snapshot not affected by pr group
  gitops/snapshot.go
  gitops/snapshot_test.go
  go.mod
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: XL

#916 feat(STONEINTG-1003): notify PRs in group of build failure
  docs/build_pipeline_controller.md
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/snapshot/snapshot_adapter.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: size: L, size: XL

#907 feat(STONEINTG-851): allow status reports on push events
  internal/controller/integrationpipeline/integrationpipeline_adapter.go
  internal/controller/statusreport/statusreport_adapter.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
Labels: size: XS, size: M, size: S

#929 fix: group snapshot error causing panic
  internal/controller/buildpipeline/buildpipeline_adapter.go
Labels: size: XS

#936 fix(STONEINTG-1086): annotate build PLR when failing to create snapshot
  internal/controller/buildpipeline/buildpipeline_adapter.go
Labels: lgtm, size: XS

#912 feat(STONEINTG-1065): let users rerun ALL tests
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: size: M, size: XL, size: XXL

#943 fix(STONEINTG-1091): don't set commitStatus for PR/MR from forked repo
  docs/statusreport-controller.md
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
Labels: lgtm, ok-to-test, size: L

#944 feat: begin referencing status.lastPromotedImage
  gitops/snapshot.go
  internal/controller/component/component_adapter.go
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS
