Repository konflux-ci/integration-service, pull requests merged in 2024-09, with the labels that each got.

#842 feat(STONEINTG-998): support group snapshot
  docs/snapshot-controller.md
  git/github/github.go
  git/github/github_test.go
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/snapshot/snapshot_controller.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
  status/mock_status.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/status.go
  tekton/build_pipeline.go
  tekton/build_pipeline_test.go
Labels: size: XL, size: XXL

#855 fix: improve details message for notfound PLR in status report
  status/status.go
Labels: lgtm, size: XS

#858 fix(STONEINTG-998): fix pipeline as code event
  gitops/snapshot.go
  gitops/snapshot_predicate_test.go
  gitops/snapshot_test.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/statusreport/statusreport_adapter_test.go
  loader/loader_test.go
  tekton/build_pipeline.go
  tekton/build_pipeline_test.go
Labels: size: M

#863 chore(stoneintg-1023): add IS SLO availability panels
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: XXL

#862 feat(KONFLUX-3903): create pipeline to run tests in konflux
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: XL

#853 fix(Stoneintg 1018): handle invalid Gitlab api commit status update
  status/reporter_gitlab.go
Labels: lgtm, size: XS

#866 feat: add test-name param to quality-dashboard task
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: XS

#865 fix(STONEINTG-998): don't release group snapshot
  gitops/snapshot.go
Labels: size: XS

#871 chore(stoneintg-1023): change availability SLO to 24 hrs agg
  config/grafana/dashboards/integration-service-dashboard.json
Labels: lgtm, size: S

#873 fix(STONEINTG-897): don't require chains for failed build PLRs
  tekton/predicates.go
Labels: lgtm, size: XS

#881 feat: Remove test-metadata test-event-type and use integration service contexts
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: XS

#877 feat(STONEINTG-957): validate ITS if git resolver
  api/v1beta2/integrationtestscenario_webhook.go
  api/v1beta2/integrationtestscenario_webhook_test.go
Labels: lgtm, size: M

#860 feat(STONEINTG-999): report test status for group snapshot
  docs/statusreport-controller.md
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  status/format.go
  status/format_test.go
  status/mock_status.go
  status/reporter_github.go
  status/status.go
  status/status_test.go
Labels: size: L, size: XL, size: XXL

#887 feat(STONEINTG-1039): updated ITS PLRs to reflect test name
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS
