Repository konflux-ci/integration-service, pull requests merged in 2024-05, with the labels that each got.

#689 feat(stoneintg-760) remove snapshotenvironmentbinding controller
  controllers/binding/snapshotenvironmentbinding_adapter.go
  controllers/binding/snapshotenvironmentbinding_adapter_test.go
  controllers/binding/snapshotenvironmentbinding_controller.go
  controllers/binding/snapshotenvironmentbinding_controller_test.go
  controllers/binding/snapshotenvironmentbinding_suite_test.go
  controllers/controllers.go
  docs/README.md
  docs/binding-controller.md
  gitops/binding.go
  gitops/binding_test.go
  gitops/predicates.go
  gitops/predicates_test.go
Labels: lgtm, size: XXL

#688 refactor(STONEINTG-774): make ctx first param
  controllers/buildpipeline/buildpipeline_adapter.go
  controllers/buildpipeline/buildpipeline_adapter_test.go
  controllers/buildpipeline/buildpipeline_controller.go
  controllers/component/component_adapter.go
  controllers/component/component_adapter_test.go
  controllers/component/component_controller.go
  controllers/integrationpipeline/integrationpipeline_adapter.go
  controllers/integrationpipeline/integrationpipeline_adapter_test.go
  controllers/integrationpipeline/integrationpipeline_controller.go
  controllers/scenario/scenario_adapter.go
  controllers/scenario/scenario_adapter_test.go
  controllers/scenario/scenario_controller.go
  controllers/snapshot/snapshot_adapter.go
  controllers/snapshot/snapshot_adapter_test.go
  controllers/snapshot/snapshot_controller.go
  controllers/statusreport/statusreport_adapter.go
  controllers/statusreport/statusreport_adapter_test.go
  controllers/statusreport/statusreport_controller.go
  gitops/snapshot.go
  gitops/snapshot_integration_tests_status.go
  gitops/snapshot_integration_tests_status_test.go
  gitops/snapshot_test.go
  helpers/integration.go
  helpers/integration_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
  status/status.go
  tekton/integration_pipeline_test.go
Labels: size: XL, size: XXL

#684 fix(STONEINTG-828): dont' add finalizer to deleted component
  controllers/component/component_adapter.go
  controllers/component/component_controller_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: XS, size: M, size: S

#698 fix: missing CRDs due to vendoring
  Makefile
Labels: lgtm, size: XS

#700 docs: rename Appstudio to Konflux in readme
  README.md
Labels: lgtm, size: XS

#701 fix(STONEINTG-841): add v1alpha1 to v1beta2 conversion webhook
  api/v1alpha1/integrationtestscenario_conversion.go
  api/v1alpha1/integrationtestscenario_types.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
  config/crd/patches/webhook_in_integrationtestscenarios.yaml
Labels: lgtm, size: M

#687 feat(STONEINTG-674): update kubebuilder to v4
  Dockerfile
  Makefile
  PROJECT
  api/v1beta2/integrationtestscenario_suite_test.go
  cmd/main.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/buildpipeline/buildpipeline_controller.go
  internal/controller/buildpipeline/buildpipeline_controller_test.go
  internal/controller/buildpipeline/buildpipeline_suite_test.go
  internal/controller/component/component_adapter.go
  internal/controller/component/component_adapter_test.go
  internal/controller/component/component_controller.go
  internal/controller/component/component_controller_test.go
  internal/controller/component/component_suite_test.go
  internal/controller/component/predicates.go
  internal/controller/controllers.go
  internal/controller/integrationpipeline/integrationpipeline_adapter.go
  internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
  internal/controller/integrationpipeline/integrationpipeline_controller.go
  internal/controller/integrationpipeline/integrationpipeline_controller_test.go
  internal/controller/integrationpipeline/integrationpipeline_suite_test.go
  internal/controller/scenario/scenario_adapter.go
  internal/controller/scenario/scenario_adapter_test.go
  internal/controller/scenario/scenario_controller.go
  internal/controller/scenario/scenario_controller_test.go
  internal/controller/scenario/scenario_suite_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/snapshot/snapshot_controller.go
  internal/controller/snapshot/snapshot_controller_test.go
  internal/controller/snapshot/snapshot_suite_test.go
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  internal/controller/statusreport/statusreport_controller.go
  internal/controller/statusreport/statusreport_controller_test.go
  internal/controller/statusreport/statusreport_suite_test.go
  internal/controller/suite_test.go
Labels: lgtm, ok-to-test, size: S

#697 fix(KFLUXBUGS-1218): add support for pipelineRun timeouts
  internal/controller/snapshot/snapshot_adapter.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: M

#713 fix: clair-scan tekton task reference
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#714 fix: glibc CVE
  Dockerfile
Labels: lgtm, size: XS

#711 fix(STONEINTG-928): conversion of v1beta1 params
  api/v1beta1/integrationtestscenario_conversion.go
Labels: size: XS

#696 feat(stoneintg-842): Link plr console URL into gitlab commit status
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
Labels: size: XS, size: S

#694 chore: add additional logging to status report controller
  internal/controller/statusreport/statusreport_adapter.go
Labels: lgtm, size: XS

#720 Revert "fix: glibc CVE"
  Dockerfile
Labels: lgtm, size: XS

#730 chore: fix panic due to incorrect logging
  internal/controller/statusreport/statusreport_adapter.go
Labels: lgtm, size: XS

#731 feat(STONEINTG-893): use go 1.21
  .github/workflows/codecov.yml
  .github/workflows/pr.yaml
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, size: XS

#649 feat(RHTAPREL-806): update operator toolkit refrence
  gitops/gitops_suite_test.go
  gitops/snapshot.go
  gitops/snapshot_integration_tests_status.go
  gitops/snapshot_integration_tests_status_test.go
  gitops/snapshot_test.go
  go.mod
  go.sum
  helpers/helpers_suite_test.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/buildpipeline/buildpipeline_controller.go
  internal/controller/buildpipeline/buildpipeline_suite_test.go
  internal/controller/component/component_adapter.go
  internal/controller/component/component_adapter_test.go
  internal/controller/component/component_controller.go
  internal/controller/component/component_suite_test.go
  internal/controller/integrationpipeline/integrationpipeline_adapter.go
  internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
  internal/controller/integrationpipeline/integrationpipeline_controller.go
  internal/controller/integrationpipeline/integrationpipeline_suite_test.go
  internal/controller/scenario/scenario_adapter.go
  internal/controller/scenario/scenario_controller.go
  internal/controller/scenario/scenario_suite_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/snapshot/snapshot_controller.go
  internal/controller/snapshot/snapshot_controller_test.go
  internal/controller/snapshot/snapshot_suite_test.go
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  internal/controller/statusreport/statusreport_controller.go
  internal/controller/statusreport/statusreport_controller_test.go
  internal/controller/statusreport/statusreport_suite_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_suite_test.go
  release/release_suite_test.go
  status/reporter_github.go
  status/reporter_gitlab.go
  status/status.go
  tekton/build_pipeline.go
  tekton/integration_pipeline.go
  tekton/predicates.go
  tekton/tekton_suite_test.go
  tekton/utils.go
  vendor/github.com/konflux-ci/operator-toolkit/LICENSE
  vendor/github.com/konflux-ci/operator-toolkit/controller/controller.go
  vendor/github.com/konflux-ci/operator-toolkit/controller/handler.go
  vendor/github.com/konflux-ci/operator-toolkit/controller/operation.go
  vendor/github.com/konflux-ci/operator-toolkit/controller/validator.go
  vendor/github.com/konflux-ci/operator-toolkit/loader/loader.go
  vendor/github.com/konflux-ci/operator-toolkit/metadata/metadata.go
  vendor/github.com/konflux-ci/operator-toolkit/predicates/backups.go
  vendor/github.com/konflux-ci/operator-toolkit/predicates/events.go
  vendor/github.com/konflux-ci/operator-toolkit/predicates/generation.go
  vendor/github.com/konflux-ci/operator-toolkit/test/metrics.go
  vendor/github.com/konflux-ci/operator-toolkit/test/paths.go
  vendor/github.com/konflux-ci/operator-toolkit/utils/backups.go
  vendor/modules.txt
Labels: lgtm, size: L, size: XL, size: XXL

#719 feat(STONEINTG-849): write all Integration-PLR-creation errors to snapshot annotation
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, do-not-merge/work-in-progress, size: XS, size: L, size: S

#735 fix(KFLUXBUGS-1299): add delete permissions for components
  config/rbac/role.yaml
  internal/controller/snapshot/snapshot_controller.go
Labels: lgtm, size: XS

#738 chore: update build-definitions references to new org
  tekton/integration_pipeline_test.go
Labels: lgtm, size: XS

#736 fix(STONE-876): catch admission validation error
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS, size: L, size: M

#733 feat(STONEINTG-881): update GCL once push snapshot is created for component
  docs/snapshot-controller.md
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: XS

#705 fix(STONEINTG-815): remove ephemeral env cleanup code
  docs/integration_pipeline_controller.md
  docs/scenario-controller.md
  helpers/integration.go
  helpers/integration_test.go
  internal/controller/integrationpipeline/integrationpipeline_adapter.go
  internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
  internal/controller/integrationpipeline/integrationpipeline_controller.go
  internal/controller/scenario/scenario_adapter.go
  internal/controller/scenario/scenario_adapter_test.go
  internal/controller/scenario/scenario_controller.go
Labels: lgtm, size: XL

#748 fix: update glibc because of CVE
  Dockerfile
Labels: lgtm, size: XS

#746 fix(STONEINTG-861): get Konflux console name from env
  status/status.go
  status/status_test.go
Labels: size: XS

#734 chore(STONEINTG-938): Improve error reporting and log annotation value for better debuggability
  status/status.go
Labels: lgtm, size: XS

#749 Revert "fix(KFLUXBUGS-1299): add delete permissions for components"
  config/rbac/role.yaml
  internal/controller/snapshot/snapshot_controller.go
Labels: lgtm, size: XS

#753 feat(STONEINTG-860): upgrade PAC to version v0.27.0
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/go-logfmt/logfmt/CHANGELOG.md
  vendor/github.com/go-logfmt/logfmt/README.md
  vendor/github.com/go-logfmt/logfmt/decode.go
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/swag/initialism_index.go
  vendor/github.com/go-openapi/swag/string_bytes.go
  vendor/github.com/go-openapi/swag/yaml.go
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/doc.go
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/github.com/google/gnostic-models/compiler/extensions.go
  vendor/github.com/google/gnostic-models/extensions/extensions.go
  vendor/github.com/google/gnostic-models/openapiv3/annotations.pb.go
  vendor/github.com/google/gnostic-models/openapiv3/annotations.proto
  vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/apis/pipelinesascode/register.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/apis/pipelinesascode/v1alpha1/register.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/apis/pipelinesascode/v1alpha1/types.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/meminfo.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/net_tls_stat.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper_defaults.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapping.go
  vendor/github.com/stoewer/go-strcase/README.md
  vendor/github.com/stoewer/go-strcase/camel.go
  vendor/modules.txt
Labels: size: XXL

#747 Run integration test from pr
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  tekton/integration_pipeline.go
Labels: lgtm, size: L
