Repository konflux-ci/integration-service, pull requests merged in 2024-07, with the labels that each got.

#779 feat(STONEINTG-955): add metric for availability by checking github connection
  Dockerfile
  cmd/main.go
  gitops/snapshot.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/component/component_adapter.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/statusreport/statusreport_adapter.go
  pkg/metrics/githubapp.go
  pkg/metrics/githubapp_test.go
  pkg/metrics/integration.go
  pkg/metrics/integration_suite_test.go
  pkg/metrics/integration_test.go
Labels: lgtm, size: XL

#792 feat(STONEINTG-973): cleanup the unused/unreleased override snapshot
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: XS

#794 feat(STONEINTG-961): remove composite snapshot
  docs/statusreport-controller.md
  gitops/snapshot.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/component/component_adapter.go
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
Labels: lgtm, size: XL

#795 feat(STONEINTG-953): copy test and custom labels/annotations
  gitops/snapshot.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: M

#801 fix(STONEINTG-863): removed bugged snapshot concurrent requests metric
  config/grafana/dashboards/integration-service-dashboard.json
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/component/component_adapter.go
  pkg/metrics/integration.go
  pkg/metrics/integration_test.go
Labels: lgtm, size: L, size: S

#800 feat(STONEINTG-967): consider 0 ReleasePlans in 'AutoReleased' field
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: XS, size: M

#808 fix(STONEING-938): adding retryOnConflict block
  status/status.go
Labels: lgtm, size: S

#814 fix(stoneintg-924): intermittent unittest failure missing application…
  internal/controller/snapshot/snapshot_controller_test.go
Labels: lgtm, size: XS

#819 chore: remove BASE_IMAGES_DIGESTS from konflux pipelines
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#823 chore(STONEINTG-888): added CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: lgtm, size: XS, size: S

#817 feat(STONEINTG-974): filter Scenarios based on Snapshot context
  docs/snapshot-controller.md
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/statusreport/statusreport_adapter.go
Labels: size: L
