Repository konflux-ci/integration-service, pull requests merged in 2024-12, with the labels that each got.

#946 chore(STONEINTG-949): migrate service image to konflux-ci
  Makefile
  config/manager/kustomization.yaml
  config/snapshotgc/snapshotgc.yaml
  docs/pull_request_template.md
Labels: lgtm, size: XS

#949 feat(KFLUXBUGS-1889): set ITS timeouts from annotations
  api/v1beta2/integrationtestscenario_types.go
  internal/controller/snapshot/snapshot_adapter.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: M

#948 feat(STONEINTG-883): Set owner reference to application for ALL Snapshots
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/snapshot/snapshot_controller.go
  internal/controller/snapshot/snapshot_controller_test.go
Labels: lgtm, size: XS, size: S

#953 feat(STONEINTG-968): use go 1.22
  .github/workflows/codecov.yml
  .github/workflows/pr.yaml
  .tekton/integration-service-pull-request.yaml
  Dockerfile
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
Labels: lgtm, size: XS, size: XL
