Repository konflux-ci/integration-service, pull requests merged in 2024-06, with the labels that each got.

#750 feat(STONINTG-896): prevent creation of ITS with snapshot set manually
  api/v1beta2/integrationtestscenario_webhook.go
  api/v1beta2/integrationtestscenario_webhook_test.go
Labels: lgtm, size: XS

#759 feat(STONEINTG-882): make component optional in snapshot controllers
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/snapshot/snapshot_controller.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: L

#764 fix: revert glibc upgrade
  Dockerfile
Labels: lgtm, size: XS

#758 feat(STONEINTG-825): reducing cognitive complexity
  internal/controller/buildpipeline/buildpipeline_adapter.go
Labels: lgtm, size: M

#760 feat(STONEINTG-892): support new override snapshot
  docs/snapshot-controller.md
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: size: L, size: XL

#769 chore: fix names and logs more data for clarity
  status/reporter.go
  status/reporter_github.go
Labels: size: XS

#774 fix(KFLUXBUGS-1355): skip components with invalid images
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: S

#770 fix(STONEINTG-939): update checkruns correctly
  status/reporter_github.go
  status/reporter_github_test.go
Labels: lgtm, size: XS, size: M

#780 chore(dependabot): remove mbasti from reviewers
  .github/dependabot.yml
Labels: lgtm, size: XS

#754 fix: remove remaining testing environment refrences
  cache/cache.go
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
  config/rbac/role.yaml
  config/rbac/snapshotgc_rbac.yaml
  docs/scenario-controller.md
  gitops/gitops_suite_test.go
  gitops/snapshot.go
  gitops/snapshot_predicate_test.go
  internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
  internal/controller/integrationpipeline/integrationpipeline_controller.go
  internal/controller/scenario/scenario_adapter_test.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/snapshot/snapshot_controller.go
  internal/controller/statusreport/statusreport_adapter.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_suite_test.go
  loader/loader_test.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: lgtm, size: XXL

#782 fix: update component source revision during override
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: size: XS

#781 fix(STONEINTG-960): show conditions in webUI
  helpers/integration.go
  status/format.go
  status/format_test.go
Labels: lgtm, size: M

#786 chore(STONEINTG-972): update integration team members
  .github/dependabot.yml
Labels: lgtm, size: XS
