Repository konflux-ci/integration-service, pull requests merged in 2025-05, with the labels that each got.

#1118 fix(STONEINTG-1186): kustomization build failed on ArgoCD
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
Labels: lgtm, size: XS

#1123 Revert "feat(stoneintg-1165): resolve pipelineruns from scenario"
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_controller.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
  tekton/tekton_suite_test.go
  vendor/github.com/tektoncd/resolution/LICENSE
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/register.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/doc.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/register.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_defaults.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_lifecycle.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_types.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_validation.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/resolution/pkg/common/annotations.go
  vendor/github.com/tektoncd/resolution/pkg/common/context.go
  vendor/github.com/tektoncd/resolution/pkg/common/doc.go
  vendor/github.com/tektoncd/resolution/pkg/common/errors.go
  vendor/github.com/tektoncd/resolution/pkg/common/labels.go
  vendor/github.com/tektoncd/resolution/pkg/common/messages.go
  vendor/github.com/tektoncd/resolution/pkg/common/statuses.go
  vendor/modules.txt
Labels: lgtm, size: XXL

#1124 feat(STONEINTG-1180): upgrade go to 1.23
  .github/workflows/codecov.yml
  .github/workflows/pr.yaml
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
  Dockerfile
  go.mod
Labels: lgtm, size: XS

#1127 Unrevert "feat(stoneintg-1165): resolve pipelineruns from scenario""
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_controller.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
  tekton/tekton_suite_test.go
  vendor/github.com/tektoncd/resolution/LICENSE
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/register.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/doc.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/register.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_defaults.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_lifecycle.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_types.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_validation.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/resolution/pkg/common/annotations.go
  vendor/github.com/tektoncd/resolution/pkg/common/context.go
  vendor/github.com/tektoncd/resolution/pkg/common/doc.go
  vendor/github.com/tektoncd/resolution/pkg/common/errors.go
  vendor/github.com/tektoncd/resolution/pkg/common/labels.go
  vendor/github.com/tektoncd/resolution/pkg/common/messages.go
  vendor/github.com/tektoncd/resolution/pkg/common/statuses.go
  vendor/modules.txt
Labels: lgtm, size: XXL

#1121 fix: update permissions for resolutionrequests
  cmd/main.go
  config/rbac/tekton_editor_role.yaml
  go.mod
  go.sum
  tekton/integration_pipeline.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/register.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/doc.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/register.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/resolution_request_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/resolution_request_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/resolution_request_lifecycle.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/resolution_request_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/resolution_request_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/annotations.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/context.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/doc.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/errors.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/interface.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/labels.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/messages.go
  vendor/github.com/tektoncd/pipeline/pkg/resolution/common/statuses.go
  vendor/modules.txt
Labels: lgtm, size: XXL

#1132 fix: canceled status of snapshot should be considered as finished
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: XS

#1133 fix: prevent nil-pointer error when ITS status isn't set
  helpers/scenario.go
  helpers/scenario_test.go
Labels: lgtm, size: XS

#1138 fix: update gitlint ignore author
  .gitlint
Labels: lgtm, size: XS

#1143 fix: update expired tasks that are failing ec
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#1130 feat: store pipeline status in oci artifact
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: size: XS

#1152 hotfix: ignore admission webhooks for integrationtestscenarios
  dist/chart/templates/webhook/webhooks.yaml
Labels: size: XS

#1153 fix: give integrationservice admins all persmissions on scenario/status
  config/rbac/integrationtestscenario_admin_role.yaml
  dist/chart/templates/rbac/integrationtestscenario_admin_role.yaml
Labels: size: XS

#1151 fix: race condition in pipelinerun creation
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS
