Repository konflux-ci/integration-service, pull requests merged in 2025-08, with the labels that each got.

#1242 fix(stoneintg-1292): fix unittest OwnerReference on Snapshot
  internal/controller/snapshot/snapshot_controller_test.go
  stoneintg-1292
Labels: size: XS, size: S

#1229 feat: use kind cluster for e2e testing
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: size: L

#1244 fix(KONFLUX-9147): don't notify group failure if not latest build
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
Labels: size: M, size: XL

#1236 feat(STONEINTG-1215): new serviceaccount for integration pipelineRuns
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  tekton/consts/consts.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: size: XS
