Repository konflux-ci/integration-service, pull requests merged in 2025-01, with the labels that each got.

#975 fix(STONEINTG-1110): fix for IsSnapshotCreatedByPACPushEvent
  gitops/snapshot.go
  gitops/snapshot_test.go
Labels: lgtm, size: XS

#988 chore: remove JVM related results
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#987 feat(STONEINTG-1096): move pr group name from summary to text
  status/format.go
  status/format_test.go
  status/status.go
Labels: lgtm, size: S

#977 fix(KONFLUX-5949): prevent pipelineRun timeout validation failures
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
Labels: lgtm, ok-to-test, size: XS

#981 feat(KONFLUX-5971): set intg test status in git according to PR bld PLR
  docs/build_pipeline_controller.md
  gitops/snapshot.go
  helpers/build.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/buildpipeline/buildpipeline_controller.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/statusreport/statusreport_adapter.go
  pkg/integrationteststatus/integration_test_status.go
  pkg/integrationteststatus/integrationteststatus_enumer.go
  status/reporter_github.go
  status/reporter_gitlab.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: XL

#994 feat(KFLUXDP-109): enable test-results-analyzer
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: S

#995 fix(STONEINTG-1096): remove pr name from integration test report title
  internal/controller/statusreport/statusreport_adapter.go
Labels: lgtm, size: XS

#999 chore(RELEASE-1227): remove owner and labels on created releases
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: S

#993 fix(STONEINTG-1087): retry longer to fetch App from ITS, and stop processing if not found
  internal/controller/scenario/scenario_adapter.go
  internal/controller/scenario/scenario_adapter_test.go
  internal/controller/scenario/scenario_controller.go
  internal/controller/scenario/scenario_controller_test.go
Labels: lgtm, size: XS, size: M, size: S

#1002 feat(STONEINTG-1068): add SHA value in Release CR name
  gitops/snapshot.go
  internal/controller/snapshot/snapshot_adapter.go
  release/releaseplan.go
  release/releaseplan_test.go
Labels: lgtm, size: M, size: S
