Repository konflux-ci/integration-service, pull requests merged in 2025-04, with the labels that each got.

#1084 fix(STONEINTG-1174): fix for unexpected pr group status report
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/snapshot/snapshot_adapter.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: XS

#1086 fix(STONEINTG-1174):apply application label when getting resources
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: M

#1072 feat: add Helm chart
  .github/workflows/test-chart.yml
  PROJECT
  dist/chart/.helmignore
  dist/chart/Chart.yaml
  dist/chart/templates/_helpers.tpl
  dist/chart/templates/certmanager/certificate.yaml
  dist/chart/templates/crd/appstudio.redhat.com_integrationtestscenarios.yaml
  dist/chart/templates/manager/manager-config.yaml
  dist/chart/templates/manager/manager.yaml
  dist/chart/templates/metrics/metrics-service.yaml
  dist/chart/templates/namespace/namespace.yaml
  dist/chart/templates/network-policy/allow-metrics-traffic.yaml
  dist/chart/templates/network-policy/allow-webhook-traffic.yaml
  dist/chart/templates/prometheus/monitor.yaml
  dist/chart/templates/prometheus/secret.yaml
  dist/chart/templates/rbac/integrationtestscenario_admin_role.yaml
  dist/chart/templates/rbac/integrationtestscenario_editor_role.yaml
  dist/chart/templates/rbac/integrationtestscenario_viewer_role.yaml
  dist/chart/templates/rbac/leader_election_role.yaml
  dist/chart/templates/rbac/leader_election_role_binding.yaml
  dist/chart/templates/rbac/metrics_auth_role.yaml
  dist/chart/templates/rbac/metrics_auth_role_binding.yaml
  dist/chart/templates/rbac/metrics_reader_role.yaml
  dist/chart/templates/rbac/prometheus_role_binding.yaml
  dist/chart/templates/rbac/prometheus_service_account.yaml
  dist/chart/templates/rbac/prometheus_viewer_role.yaml
  dist/chart/templates/rbac/role.yaml
  dist/chart/templates/rbac/role_binding.yaml
  dist/chart/templates/rbac/service_account.yaml
  dist/chart/templates/rbac/snapshotgc_rbac.yaml
  dist/chart/templates/rbac/tekton_editor_role.yaml
  dist/chart/templates/rbac/tekton_role_binding.yaml
  dist/chart/templates/snapshotgc/snapshotgc.yaml
  dist/chart/templates/webhook/service.yaml
  dist/chart/templates/webhook/webhooks.yaml
  dist/chart/values.schema.json
  dist/chart/values.yaml
Labels: lgtm, size: XXL

#1095 feat(): add pac.test.appstudio.openshift.io/cancelled annotation to
  gitops/snapshot.go
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#1091 feat(STONEINTG-1164): add ResolverType to ITS api
  api/v1beta2/integrationtestscenario_types.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
Labels: lgtm, size: XS

#1090 feat(STONEINTG-1144): report group snapshot creation failure to git provider
  docs/statusreport-controller.md
  gitops/snapshot.go
  gitops/snapshot_predicate_test.go
  gitops/snapshot_test.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/statusreport/statusreport_adapter.go
  internal/controller/statusreport/statusreport_adapter_test.go
  internal/controller/statusreport/statusreport_controller.go
  internal/controller/statusreport/statusreport_controller_test.go
  pkg/integrationteststatus/integration_test_status.go
  pkg/integrationteststatus/integrationteststatus_enumer.go
  status/reporter_github.go
  status/reporter_github_test.go
  status/reporter_gitlab.go
  status/reporter_gitlab_test.go
  status/status.go
  status/status_test.go
Labels: lgtm, size: L, size: XL

#1103 chore: Offboard Dheeraj from Integration Service
  .github/CODEOWNERS
Labels: lgtm, size: XS

#1104 fix(ASC-783): support new label for konflux tenant namespaces
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: XS

#1107 fix(STONEINTG-1186): fix target of IS is missing
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/prometheus/monitor.yaml
Labels: lgtm, size: XS

#1112 fix: change ResolverType field to ResouceKind
  api/v1beta2/integrationtestscenario_types.go
  config/crd/bases/appstudio.redhat.com_integrationtestscenarios.yaml
Labels: lgtm, size: XS

#1099 chore(stoneintg-1191): make "pipeline" the default resolver type in ITS
  api/v1beta2/integrationtestscenario_webhook.go
  api/v1beta2/integrationtestscenario_webhook_test.go
  api/v1beta2/zz_generated.deepcopy.go
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  dist/chart/templates/webhook/webhooks.yaml
Labels: lgtm, size: XS, size: L, size: M

#1115 fix(KFLUXSPRT-2829): show latest integration plr in github UI
  git/github/github.go
  internal/controller/snapshot/snapshot_adapter.go
Labels: lgtm, size: XS

#1092 feat(stoneintg-1165): resolve pipelineruns from scenario
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_controller.go
  tekton/integration_pipeline.go
  tekton/integration_pipeline_test.go
  tekton/tekton_suite_test.go
  vendor/github.com/tektoncd/resolution/LICENSE
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/register.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/doc.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/register.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_defaults.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_lifecycle.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_types.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/resolution_request_validation.go
  vendor/github.com/tektoncd/resolution/pkg/apis/resolution/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/resolution/pkg/common/annotations.go
  vendor/github.com/tektoncd/resolution/pkg/common/context.go
  vendor/github.com/tektoncd/resolution/pkg/common/doc.go
  vendor/github.com/tektoncd/resolution/pkg/common/errors.go
  vendor/github.com/tektoncd/resolution/pkg/common/labels.go
  vendor/github.com/tektoncd/resolution/pkg/common/messages.go
  vendor/github.com/tektoncd/resolution/pkg/common/statuses.go
  vendor/modules.txt
Labels: lgtm, size: M, size: XXL
