Repository konflux-ci/integration-service, pull requests merged in 2025-07, with the labels that each got.

#1190 chore: enlarge timeout for the test EnsureIntegrationPipelineRunLogURL
  internal/controller/integrationpipeline/integrationpipeline_adapter_test.go
Labels: lgtm, size: XS

#1191 fix(STONEINTG-1248) adjust non-pr-snapshots count for gc
  config/snapshotgc/snapshotgc.yaml
  dist/chart/values.yaml
Labels: lgtm, size: XS

#1210 fix(stoneintg-1256): resolutionrequests make integration service hang
  tekton/integration_pipeline.go
Labels: size: S

#1212 feat: add validation webhook for snapshot component immutability
  cmd/main.go
  config/webhook/manifests.yaml
  internal/controller/snapshot/snapshot_controller_test.go
  internal/webhook/v1beta2/snapshot_webhook.go
  internal/webhook/v1beta2/snapshot_webhook_test.go
  internal/webhook/v1beta2/snapshot_webhook_unit_test.go
  internal/webhook/v1beta2/webhook_suite_test.go
Labels: size: XL, size: XXL

#1213 Enable ARM64 builds for integration-service
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: size: M

#1226 fix(stoneintg-1187): Prevent 'resource name empty' error
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: size: XS

#1230 chore: add Nigel to the codeowners config
  .github/CODEOWNERS
Labels: size: XS
