Repository konflux-ci/integration-service, pull requests merged in 2025-03, with the labels that each got.

#1045 chore: remove Pat from integration-service's CODEOWNERS
  .github/CODEOWNERS
Labels: lgtm, size: XS

#1020 feat(STONEINTG-1050): cancel old intg pipelineruns
  gitops/snapshot.go
  helpers/integration.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
Labels: lgtm, size: L, size: XL

#1051 feat(): use always sealights images for testing purpose
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: XS

#1053 feat(STONEINTG-1135): add unicode and shell check tasks
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: L, size: M

#1058 fix(STONEINTG-1050): annotation correction
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
Labels: lgtm, size: XS, size: M, size: S

#1061 feat(STONEINTG-569): get pac secret and private key name from config
  status/reporter_github.go
  status/reporter_github_test.go
Labels: lgtm, size: XS, size: S

#1062 fix: do not store SL token
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#1049 feat(STONEINTG-1131): initialize pending intg status for group ITS
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  internal/controller/statusreport/statusreport_adapter.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
  status/mock_status.go
  status/status.go
  status/status_test.go
  tekton/build_pipeline.go
  tekton/build_pipeline_test.go
Labels: lgtm, size: XL, size: XXL

#1064 fix(STONEINTG-1131): requeue initializing intg status when pr group info is not found in build PLR
  internal/controller/buildpipeline/buildpipeline_adapter.go
  internal/controller/buildpipeline/buildpipeline_adapter_test.go
Labels: lgtm, size: S

#1067 feat(STONEINTG-1141): cancel older group snapshot and its intg plr
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/snapshot/snapshot_adapter.go
  internal/controller/snapshot/snapshot_adapter_test.go
  loader/loader.go
  loader/loader_mock.go
  loader/loader_mock_test.go
  loader/loader_test.go
Labels: lgtm, size: XL

#1071 fix(STONEINTG-996): adjust bld PLR ensure fucntions sequence in ctrl
  internal/controller/buildpipeline/buildpipeline_controller.go
Labels: lgtm, size: XS

#1076 fix(STONEINTG-1131): fix for nil returned ITS
  internal/controller/buildpipeline/buildpipeline_adapter.go
Labels: lgtm, size: XS

#1078 fix(STONEINTG-1141): fix sortSnapshot for group snapshot
  gitops/snapshot.go
  gitops/snapshot_test.go
  internal/controller/snapshot/snapshot_adapter_test.go
Labels: lgtm, size: S

#1081 feat(): enable Sealights plugin for integration service
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: XS
