Repository konflux-ci/integration-service, pull requests merged in 2025-02, with the labels that each got.

#998 feat(STONEINTG-1116): migrate build PLR to ta version
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XL

#1012 fix(STONEINTG-1125): fix gitlab commitStatus change from pending to pending
  status/reporter_gitlab.go
Labels: lgtm, size: XS

#1017 feat(STONEINTG-1123): log error when failing to report status for completed integration pipelinerun
  internal/controller/statusreport/statusreport_adapter.go
Labels: size: XS

#1006 feat(KFLUXDP-107): Integrate Sealights tasks into integration service pipelines
  .dockerignore
  .tekton/integration-service-pull-request.yaml
  .tekton/integration-service-push.yaml
  Dockerfile
  integration-tests/pipelines/konflux-e2e-tests.yaml
Labels: lgtm, size: L, size: M

#1015 fix(stoneintg-1017): validate git resolver in integration test scenario
  api/v1beta2/integrationtestscenario_types_test.go
  api/v1beta2/integrationtestscenario_webhook.go
  api/v1beta2/integrationtestscenario_webhook_test.go
Labels: lgtm, size: L, size: M

#1023 fix: use same tekton task version to build pristine image and sealights images in push events
  .tekton/integration-service-push.yaml
Labels: lgtm, size: XS

#1038 fix(STONEINTG-1136): garbage collector checks konflux user namespaces
  cmd/snapshotgc/snapshotgc.go
  cmd/snapshotgc/snapshotgc_test.go
Labels: lgtm, size: XS

#1035 chore(stoneintg-1134): update github workflows to ubuntu-24.04
  .github/workflows/codecov.yml
  .github/workflows/pr.yaml
Labels: lgtm, size: XS
